"""
Template engine for obsidian-brain.
Provides reusable note templates for agents.
"""

from pathlib import Path
from typing import Optional
from datetime import datetime


DEFAULT_TEMPLATE = """---
created: {created}
agent: {agent}
tags: [{tags}]
---

# {title}

> Agent: **{agent}** · {created}

{content}

---

*Auto-generated by obsidian-brain*
"""


class TemplateEngine:
    """
    Manages note templates for consistent structure.
    """

    def __init__(self, template_dir: str = "templates"):
        self.template_dir = Path(template_dir)
        self._templates: dict = {}

    def register(self, name: str, template: str):
        """Register a named template."""
        self._templates[name] = template

    def render(
        self,
        name: str,
        agent: str,
        title: str,
        content: str,
        tags: list,
        **kwargs,
    ) -> str:
        """Render a template with provided data."""
        template = self._templates.get(name, DEFAULT_TEMPLATE)
        return template.format(
            agent=agent,
            title=title,
            content=content,
            tags=", ".join(f'"{t}"' for t in tags),
            created=datetime.now().strftime("%Y-%m-%d %H:%M"),
            **kwargs,
        )

    def load_from_dir(self, path: Optional[str] = None):
        """Load templates from a directory."""
        template_path = Path(path) if path else self.template_dir
        if not template_path.exists():
            return

        for tmpl_file in template_path.glob("*.tmpl"):
            name = tmpl_file.stem
            with open(tmpl_file, "r", encoding="utf-8") as f:
                self._templates[name] = f.read()
